version: '3'
services:
  c1:
    build: h
    environment:
      - REGISTER=h2:/compose-test
      - ENTRYPOINT=ndnping /compose-test/test > /generated/ping.log && tail -f /generated/ping.log
    container_name: c1
    depends_on:
      - p1
      - h2
    volumes:
      - ./generated/c1:/generated
  c2:
    build: h
    environment:
      - REGISTER=h2:/compose-test
      - ENTRYPOINT=ndnping /compose-test/test > /generated/ping.log && tail -f /generated/ping.log
    container_name: c2
    depends_on:
      - p1
      - h2
    volumes:
      - ./generated/c2:/generated
  c3:
    build: h
    environment:
      - REGISTER=h3:/compose-test
      - ENTRYPOINT=ndnping /compose-test/test > /generated/ping.log && tail -f /generated/ping.log
    container_name: c3
    depends_on:
      - p1
      - h3
    volumes:
      - ./generated/c3:/generated
  c4:
    build: h
    environment:
      - REGISTER=h3:/compose-test
      - ENTRYPOINT=ndnping /compose-test/test > /generated/ping.log && tail -f /generated/ping.log
    container_name: c4
    depends_on:
      - p1
      - h3
    volumes:
      - ./generated/c4:/generated
  h1:
    build: h
    environment:
      - NFD_BACKGROUND=no
      - REGISTER=p1:/compose-test
    container_name: h1
    depends_on:
      - p1
    volumes:
      - ./generated/h1:/generated
  h2:
    build: h
    environment:
      - NFD_BACKGROUND=no
      - REGISTER=h1:/compose-test
    container_name: h2
    depends_on:
      - h1
    volumes:
      - ./generated/h2:/generated
  h3:
    build: h
    environment:
      - NFD_BACKGROUND=no
      - REGISTER=h1:/compose-test
    container_name: h3
    depends_on:
      - h1
    volumes:
      - ./generated/h3:/generated
  p1:
    build: h
    environment:
      - ENTRYPOINT=ndnpingserver /compose-test/test > /generated/ping.log && tail -f /generated/ping.log
    container_name: p1
    volumes:
      - ./generated/p1:/generated
